version: "3.9"

services:

  cerebri:

    environment:
      - DISPLAY=$DISPLAY
      - RUN_VNC=false
      - RUN_ZETH=false
    image: ${REGISTRY}/cognipilot/cerebri:${TAG}
    build:
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    hostname: cerebri
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./workdir:/workdir
      - /tmp/.X11-unix:/tmp/.X11-unix
