version: "3.9"

volumes:

    # remembers gz config, downloaded models etc
    gz_config:

services:

  dream:

    environment:
      - DISPLAY=$DISPLAY
      - RUN_VNC=false
      - RUN_ZETH=true
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
    image: ${REGISTRY}/cognipilot/dream:${TAG}
    build:
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    hostname: dream
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - /dev/bus/usb/:/dev/bus/usb
      - ./work:/home/user/work
      - gz_config:/home/user/.gz
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
      - $HOME/.gnupg:/home/user/.gnupg
      - $HOME/.ssh:/home/user/.ssh
      - $HOME/.gitconfig:/home/user/.gitconfig
