version: "3.9"

volumes:

    # remembers gz config, downloaded models etc
    gz_config:

networks:
  static_network:
    ipam:
        config:
          - subnet: 172.20.0.0/16

services:

  dream:
    networks:
      static_network:
        ipv4_address: 172.20.128.2
    ports:
      - 8888:8888
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
      - DISPLAY=$DISPLAY
      - RUN_VNC=false
      - RUN_ZETH=true
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
    image: ${REGISTRY}/cognipilot/dream:${TAG}
    build:
      dockerfile: Dockerfile
    tty: true
    ipc: host
    stdin_open: true
    privileged: true
    hostname: dream
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./work:/home/user/work
      - gz_config:/home/user/.gz
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.gnupg:/home/user/.gnupg
      - $HOME/.ssh:/home/user/.ssh
      - $HOME/.gitconfig:/home/user/.gitconfig
