#!/bin/bash
set -e

echo Setup Helmet for MRBuggy3 SITL
pushd ~/work
if [ ! -d helmet ] ; then
  git clone git@github.com:CogniPilot/helmet
fi
vcs import < helmet/dream/base.yaml
vcs import < helmet/dream/mrbuggy3.yaml
popd

echo Build Cranium
pushd ~/work/cranium
colcon build --symlink-install
. ./install/setup.sh
popd

echo Build Cerebri for MRBuggy3 SITL
pushd ~/work/ws/cerebri
if [ ! -d ~/work/ws/.west ] ; then
  west init -l .
fi
west update
west build app/mrbuggy3/ -b native_posix -t install -p
. ./install/setup.sh
popd

echo Build Cyecca
pushd ~/work/cyecca
poetry install
popd
