#!/bin/bash
set -e
if [ ! -d ~/work/cyecca ] ; then
  git clone git@github.com:cognipilot/cyecca ~/work/cyecca
fi
if [ ! -d ~/work/cranium/src/cyecca_ros ] ; then
  git clone git@github.com:cognipilot/cyecca_ros ~/work/cranium/src/cyecca_ros
fi

cd ~/work/cyecca
poetry install
poetry run jupyter lab
